#!/bin/sh

set -e

challenge=$(basename $1 .rb)

test -f spec/${challenge}_spec.rb && exit 0

cp tools/skel_spec.rb spec/${challenge}_spec.rb
sed -i -e "s/Skel/${challenge}/g" spec/${challenge}_spec.rb
